language: generic
env:
  global:
    - SSH_KEY="travis_key"
    - GIT_NAME="Josh Chase"
    - GIT_EMAIL="josh@jec.pw"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="hugo"
script:
  - "./bin/hugo"
after_success:
  - echo "blog.jec.pw" > ./public/CNAME
  - ./bin/deploy.sh
before_install:
  - openssl aes-256-cbc -K $encrypted_d5012ebcb4d2_key -iv $encrypted_d5012ebcb4d2_iv -in travis_key.enc -out travis_key -d
